os: osx
osx_image: xcode12.3
language: swift
script: xcodebuild clean build test -workspace VeryUsefulToolstoRemember/VeryUsefulToolstoRemember.xcworkspace -scheme "VeryUsefulToolstoRemember" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone SE (2nd generation),OS=14.3'